"""Add canonical data models for Phase 30

Revision ID: 11665ac87e79
Revises: 39004d799609
Create Date: 2026-09-23 22:06:03.211007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11665ac87e79'
down_revision: Union[str, Sequence[str], None] = '39004d799609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_snapshots_id'), 'dataset_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_dataset_snapshots_snapshot_hash'), 'dataset_snapshots', ['snapshot_hash'], unique=True)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('dataset_type', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('instrument_universe_hash', sa.String(length=64), nullable=True),
    sa.Column('rows_received', sa.Integer(), nullable=True),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('rows_updated', sa.Integer(), nullable=True),
    sa.Column('rows_rejected', sa.Integer(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('code_sha', sa.String(length=40), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_id'), 'ingestion_runs', ['id'], unique=False)
    op.create_table('trading_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_name', sa.String(length=50), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('is_trading_day', sa.Boolean(), nullable=False),
    sa.Column('session_open', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_close', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_name', 'session_date', name='uq_trading_session_date')
    )
    op.create_index(op.f('ix_trading_sessions_calendar_name'), 'trading_sessions', ['calendar_name'], unique=False)
    op.create_index(op.f('ix_trading_sessions_id'), 'trading_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_trading_sessions_session_date'), 'trading_sessions', ['session_date'], unique=False)
    op.create_table('benchmark_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benchmark_name', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('benchmark_name', 'date', name='uq_benchmark_name_date')
    )
    op.create_index(op.f('ix_benchmark_series_benchmark_name'), 'benchmark_series', ['benchmark_name'], unique=False)
    op.create_index(op.f('ix_benchmark_series_date'), 'benchmark_series', ['date'], unique=False)
    op.create_index(op.f('ix_benchmark_series_id'), 'benchmark_series', ['id'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('is_applied', sa.Boolean(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'ex_date', 'action_type', name='uq_corporate_action_exdate_type')
    )
    op.create_index(op.f('ix_corporate_actions_ex_date'), 'corporate_actions', ['ex_date'], unique=False)
    op.create_index(op.f('ix_corporate_actions_id'), 'corporate_actions', ['id'], unique=False)
    op.create_index(op.f('ix_corporate_actions_instrument_id'), 'corporate_actions', ['instrument_id'], unique=False)
    op.create_table('historical_fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_pair', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_pair', 'date', name='uq_historical_fx_pair_date')
    )
    op.create_index(op.f('ix_historical_fx_rates_currency_pair'), 'historical_fx_rates', ['currency_pair'], unique=False)
    op.create_index(op.f('ix_historical_fx_rates_date'), 'historical_fx_rates', ['date'], unique=False)
    op.create_index(op.f('ix_historical_fx_rates_id'), 'historical_fx_rates', ['id'], unique=False)
    op.create_table('instrument_universe_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('universe_name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_universe_history_end_date'), 'instrument_universe_history', ['end_date'], unique=False)
    op.create_index(op.f('ix_instrument_universe_history_id'), 'instrument_universe_history', ['id'], unique=False)
    op.create_index(op.f('ix_instrument_universe_history_instrument_id'), 'instrument_universe_history', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_instrument_universe_history_start_date'), 'instrument_universe_history', ['start_date'], unique=False)
    op.create_index(op.f('ix_instrument_universe_history_universe_name'), 'instrument_universe_history', ['universe_name'], unique=False)
    op.add_column('calibration_cycles', sa.Column('dataset_snapshot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calibration_cycles', 'dataset_snapshots', ['dataset_snapshot_id'], ['id'])
    op.add_column('fundamental_data', sa.Column('revision', sa.Integer(), server_default='0', nullable=False))
    op.add_column('fundamental_data', sa.Column('ingestion_run_id', sa.Integer(), nullable=True))
    op.add_column('fundamental_data', sa.Column('provenance_type', sa.String(length=30), server_default='UNKNOWN', nullable=False))
    op.drop_constraint(op.f('uq_fundamental_instrument_period'), 'fundamental_data', type_='unique')
    op.create_unique_constraint('uq_fundamental_instrument_period_rev', 'fundamental_data', ['instrument_id', 'period', 'revision'])
    op.create_foreign_key(None, 'fundamental_data', 'ingestion_runs', ['ingestion_run_id'], ['id'])
    op.add_column('ohlcv_daily', sa.Column('ingestion_run_id', sa.Integer(), nullable=True))
    op.add_column('ohlcv_daily', sa.Column('provenance_type', sa.String(length=30), server_default='UNKNOWN', nullable=False))
    op.add_column('ohlcv_daily', sa.Column('is_adjusted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('ohlcv_daily', sa.Column('session_type', sa.String(length=20), nullable=True))
    op.add_column('ohlcv_daily', sa.Column('source_record_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'ohlcv_daily', 'ingestion_runs', ['ingestion_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ohlcv_daily_ingestion_run_id_fkey', 'ohlcv_daily', type_='foreignkey')
    op.drop_column('ohlcv_daily', 'source_record_id')
    op.drop_column('ohlcv_daily', 'session_type')
    op.drop_column('ohlcv_daily', 'is_adjusted')
    op.drop_column('ohlcv_daily', 'provenance_type')
    op.drop_column('ohlcv_daily', 'ingestion_run_id')
    op.drop_constraint('fundamental_data_ingestion_run_id_fkey', 'fundamental_data', type_='foreignkey')
    op.drop_constraint('uq_fundamental_instrument_period_rev', 'fundamental_data', type_='unique')
    op.create_unique_constraint(op.f('uq_fundamental_instrument_period'), 'fundamental_data', ['instrument_id', 'period'], postgresql_nulls_not_distinct=False)
    op.drop_column('fundamental_data', 'provenance_type')
    op.drop_column('fundamental_data', 'ingestion_run_id')
    op.drop_column('fundamental_data', 'revision')
    op.drop_constraint('calibration_cycles_dataset_snapshot_id_fkey', 'calibration_cycles', type_='foreignkey')
    op.drop_column('calibration_cycles', 'dataset_snapshot_id')
    op.drop_index(op.f('ix_instrument_universe_history_universe_name'), table_name='instrument_universe_history')
    op.drop_index(op.f('ix_instrument_universe_history_start_date'), table_name='instrument_universe_history')
    op.drop_index(op.f('ix_instrument_universe_history_instrument_id'), table_name='instrument_universe_history')
    op.drop_index(op.f('ix_instrument_universe_history_id'), table_name='instrument_universe_history')
    op.drop_index(op.f('ix_instrument_universe_history_end_date'), table_name='instrument_universe_history')
    op.drop_table('instrument_universe_history')
    op.drop_index(op.f('ix_historical_fx_rates_id'), table_name='historical_fx_rates')
    op.drop_index(op.f('ix_historical_fx_rates_date'), table_name='historical_fx_rates')
    op.drop_index(op.f('ix_historical_fx_rates_currency_pair'), table_name='historical_fx_rates')
    op.drop_table('historical_fx_rates')
    op.drop_index(op.f('ix_corporate_actions_instrument_id'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_id'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_ex_date'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index(op.f('ix_benchmark_series_id'), table_name='benchmark_series')
    op.drop_index(op.f('ix_benchmark_series_date'), table_name='benchmark_series')
    op.drop_index(op.f('ix_benchmark_series_benchmark_name'), table_name='benchmark_series')
    op.drop_table('benchmark_series')
    op.drop_index(op.f('ix_trading_sessions_session_date'), table_name='trading_sessions')
    op.drop_index(op.f('ix_trading_sessions_id'), table_name='trading_sessions')
    op.drop_index(op.f('ix_trading_sessions_calendar_name'), table_name='trading_sessions')
    op.drop_table('trading_sessions')
    op.drop_index(op.f('ix_ingestion_runs_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_dataset_snapshots_snapshot_hash'), table_name='dataset_snapshots')
    op.drop_index(op.f('ix_dataset_snapshots_id'), table_name='dataset_snapshots')
    op.drop_table('dataset_snapshots')
    # ### end Alembic commands ###
