"""Add source observation layers and fix provenance constraints

Revision ID: 3d07f1bd8877
Revises: 11665ac87e79
Create Date: 2026-09-23 23:02:29.813763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d07f1bd8877'
down_revision: Union[str, Sequence[str], None] = '11665ac87e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlcv_source_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('provider_symbol', sa.String(length=100), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('is_adjusted', sa.Boolean(), nullable=False),
    sa.Column('price_basis', sa.String(length=50), server_default='RAW', nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'timestamp', 'provider_name', 'is_adjusted', 'ingestion_run_id', name='uq_ohlcv_source_obs')
    )
    op.create_index(op.f('ix_ohlcv_source_observations_id'), 'ohlcv_source_observations', ['id'], unique=False)
    op.create_index(op.f('ix_ohlcv_source_observations_ingestion_run_id'), 'ohlcv_source_observations', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_ohlcv_source_observations_instrument_id'), 'ohlcv_source_observations', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_ohlcv_source_observations_timestamp'), 'ohlcv_source_observations', ['timestamp'], unique=False)
    op.drop_constraint(op.f('uq_benchmark_name_date'), 'benchmark_series', type_='unique')
    op.create_unique_constraint('uq_benchmark_name_date_prov', 'benchmark_series', ['benchmark_name', 'date', 'provider_name'])
    op.drop_constraint(op.f('uq_historical_fx_pair_date'), 'historical_fx_rates', type_='unique')
    op.create_unique_constraint('uq_historical_fx_pair_date_prov', 'historical_fx_rates', ['currency_pair', 'date', 'provider_name'])
    op.add_column('trading_sessions', sa.Column('session_type', sa.String(length=50), server_default='REGULAR', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trading_sessions', 'session_type')
    op.drop_constraint('uq_historical_fx_pair_date_prov', 'historical_fx_rates', type_='unique')
    op.create_unique_constraint(op.f('uq_historical_fx_pair_date'), 'historical_fx_rates', ['currency_pair', 'date'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_benchmark_name_date_prov', 'benchmark_series', type_='unique')
    op.create_unique_constraint(op.f('uq_benchmark_name_date'), 'benchmark_series', ['benchmark_name', 'date'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_ohlcv_source_observations_timestamp'), table_name='ohlcv_source_observations')
    op.drop_index(op.f('ix_ohlcv_source_observations_instrument_id'), table_name='ohlcv_source_observations')
    op.drop_index(op.f('ix_ohlcv_source_observations_ingestion_run_id'), table_name='ohlcv_source_observations')
    op.drop_index(op.f('ix_ohlcv_source_observations_id'), table_name='ohlcv_source_observations')
    op.drop_table('ohlcv_source_observations')
    # ### end Alembic commands ###
