"""add_position_lifecycle

Revision ID: 5a09821a85e9
Revises: f95a6200b76f
Create Date: 2026-09-20 21:32:17.138124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5a09821a85e9'
down_revision: Union[str, Sequence[str], None] = 'f95a6200b76f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_lifecycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('health_state', sa.Enum('STABLE', 'WATCH', 'CONFIRMED_DETERIORATION', 'RECOVERING', 'CLOSED', name='lifecyclehealthstate'), nullable=False),
    sa.Column('recommended_action', sa.Enum('HOLD', 'CONSIDER_ADD', 'CONSIDER_REDUCE', 'CONSIDER_EXIT', 'NO_ACTION_DATA', name='lifecycleaction'), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('negative_confirmation_count', sa.Integer(), nullable=False),
    sa.Column('strong_sell_confirmation_count', sa.Integer(), nullable=False),
    sa.Column('recovery_confirmation_count', sa.Integer(), nullable=False),
    sa.Column('add_confirmation_count', sa.Integer(), nullable=False),
    sa.Column('last_counted_market_observation_key', sa.String(), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_transition_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('episode_started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'instrument_id', name='uq_position_lifecycle_port_inst')
    )
    
    
    
    op.create_table('position_lifecycle_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lifecycle_id', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('market_observation_key', sa.String(), nullable=False),
    sa.Column('portfolio_context_key', sa.String(), nullable=False),
    sa.Column('health_state_before', sa.Enum('STABLE', 'WATCH', 'CONFIRMED_DETERIORATION', 'RECOVERING', 'CLOSED', name='lifecyclehealthstate'), nullable=True),
    sa.Column('health_state_after', sa.Enum('STABLE', 'WATCH', 'CONFIRMED_DETERIORATION', 'RECOVERING', 'CLOSED', name='lifecyclehealthstate'), nullable=False),
    sa.Column('recommended_action', sa.Enum('HOLD', 'CONSIDER_ADD', 'CONSIDER_REDUCE', 'CONSIDER_EXIT', 'NO_ACTION_DATA', name='lifecycleaction'), nullable=False),
    sa.Column('market_view', sa.String(), nullable=True),
    sa.Column('reason_codes', sa.String(), nullable=True),
    sa.Column('evidence_data', sa.String(), nullable=True),
    sa.Column('context_data', sa.String(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lifecycle_id'], ['position_lifecycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lifecycle_id', 'episode_number', 'market_observation_key', 'portfolio_context_key', name='uq_lifecycle_snapshot_key')
    )
    
    
    
    
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position_lifecycle_snapshots')
    op.drop_table('position_lifecycles')
    
    op.execute("DROP TYPE IF EXISTS lifecyclehealthstate ")
    op.execute("DROP TYPE IF EXISTS lifecycleaction ")
    # ### end Alembic commands ###