"""phase03_ohlcv_daily

Revision ID: 5e32e9bb5438
Revises: b233039f6894
Create Date: 2026-09-06 23:53:37.134508

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e32e9bb5438"
down_revision: str | Sequence[str] | None = "b233039f6894"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ohlcv_daily",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("high", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("low", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("close", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("provider_name", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("instrument_id", "timestamp", name="uq_ohlcv_daily_instrument_time"),
    )
    op.create_index(op.f("ix_ohlcv_daily_id"), "ohlcv_daily", ["id"], unique=False)
    op.create_index(
        op.f("ix_ohlcv_daily_instrument_id"), "ohlcv_daily", ["instrument_id"], unique=False
    )
    op.create_index(op.f("ix_ohlcv_daily_timestamp"), "ohlcv_daily", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ohlcv_daily_timestamp"), table_name="ohlcv_daily")
    op.drop_index(op.f("ix_ohlcv_daily_instrument_id"), table_name="ohlcv_daily")
    op.drop_index(op.f("ix_ohlcv_daily_id"), table_name="ohlcv_daily")
    op.drop_table("ohlcv_daily")
    # ### end Alembic commands ###
