"""Add Educational Models

Revision ID: 5f12388559ec
Revises: bc68240f3e83
Create Date: 2026-09-07 15:38:43.955431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f12388559ec'
down_revision: Union[str, Sequence[str], None] = 'bc68240f3e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educational_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educational_modules_id'), 'educational_modules', ['id'], unique=False)
    op.create_index(op.f('ix_educational_modules_slug'), 'educational_modules', ['slug'], unique=True)
    op.create_table('educational_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('content_beginner', sa.Text(), nullable=False),
    sa.Column('content_detailed', sa.Text(), nullable=False),
    sa.Column('key_points', sa.String(), nullable=True),
    sa.Column('related_terms', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['educational_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educational_lessons_id'), 'educational_lessons', ['id'], unique=False)
    op.create_index(op.f('ix_educational_lessons_slug'), 'educational_lessons', ['slug'], unique=True)
    op.create_table('user_lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('last_position', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['educational_lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_lesson_progress_id'), 'user_lesson_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_lesson_progress_lesson_id'), 'user_lesson_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_user_lesson_progress_user_id'), 'user_lesson_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_lesson_progress_user_id'), table_name='user_lesson_progress')
    op.drop_index(op.f('ix_user_lesson_progress_lesson_id'), table_name='user_lesson_progress')
    op.drop_index(op.f('ix_user_lesson_progress_id'), table_name='user_lesson_progress')
    op.drop_table('user_lesson_progress')
    op.drop_index(op.f('ix_educational_lessons_slug'), table_name='educational_lessons')
    op.drop_index(op.f('ix_educational_lessons_id'), table_name='educational_lessons')
    op.drop_table('educational_lessons')
    op.drop_index(op.f('ix_educational_modules_slug'), table_name='educational_modules')
    op.drop_index(op.f('ix_educational_modules_id'), table_name='educational_modules')
    op.drop_table('educational_modules')
    # ### end Alembic commands ###
