"""Add Phase 17 behavior models

Revision ID: 67c1201262e1
Revises: e55899f9cbcb
Create Date: 2026-09-08 01:17:32.242709

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '67c1201262e1'
down_revision: str | Sequence[str] | None = 'e55899f9cbcb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fomo_tendency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('patience_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('concentration_risk', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_behavior_profiles_id'), 'behavior_profiles', ['id'], unique=False)
    op.create_table('trade_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('insight_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['portfolio_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_trade_insights_id'), 'trade_insights', ['id'], unique=False)
    op.create_index(op.f('ix_trade_insights_user_id'), 'trade_insights', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_insights_user_id'), table_name='trade_insights')
    op.drop_index(op.f('ix_trade_insights_id'), table_name='trade_insights')
    op.drop_table('trade_insights')
    op.drop_index(op.f('ix_behavior_profiles_id'), table_name='behavior_profiles')
    op.drop_table('behavior_profiles')
    # ### end Alembic commands ###
