"""Add Backtest Models

Revision ID: 7cadfe1f564b
Revises: 75021af967d1
Create Date: 2026-09-07 16:25:15.890286

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7cadfe1f564b'
down_revision: str | Sequence[str] | None = '75021af967d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('strategy_version', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('commission_pct', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('slippage_pct', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_jobs_id'), 'backtest_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_jobs_user_id'), 'backtest_jobs', ['user_id'], unique=False)
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('total_return_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('cagr_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('win_rate_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('fees_paid', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('benchmark_return_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('equity_curve', sa.Text(), nullable=True),
    sa.Column('bias_audit', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('validation_state', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['backtest_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_backtest_results_id'), 'backtest_results', ['id'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('instrument_symbol', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fees', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('slippage', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['backtest_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_trades_id'), 'backtest_trades', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_trades_result_id'), 'backtest_trades', ['result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backtest_trades_result_id'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_backtest_results_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_backtest_jobs_user_id'), table_name='backtest_jobs')
    op.drop_index(op.f('ix_backtest_jobs_id'), table_name='backtest_jobs')
    op.drop_table('backtest_jobs')
    # ### end Alembic commands ###
