"""Add manifest_json to CalibrationCycle

Revision ID: 8008f6ad50d1
Revises: 95e303bc3700
Create Date: 2026-09-22 19:01:08.286709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8008f6ad50d1'
down_revision: Union[str, Sequence[str], None] = '95e303bc3700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibration_cycles', sa.Column('manifest_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calibration_cycles', 'manifest_json')
    # ### end Alembic commands ###
