"""Add DecisionSnapshot model

Revision ID: 936aff88125b
Revises: f6b73d7d3ab3
Create Date: 2026-09-07 14:01:38.704477

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '936aff88125b'
down_revision: str | Sequence[str] | None = 'f6b73d7d3ab3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('STRONG_BUY', 'BUY', 'HOLD', 'SELL', 'STRONG_SELL', name='decisionaction'), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('reason_codes', sa.String(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_snapshots_id'), 'decision_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_decision_snapshots_instrument_id'), 'decision_snapshots', ['instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_snapshots_instrument_id'), table_name='decision_snapshots')
    op.drop_index(op.f('ix_decision_snapshots_id'), table_name='decision_snapshots')
    op.drop_table('decision_snapshots')
    op.execute("DROP TYPE IF EXISTS decisionaction")
    # ### end Alembic commands ###
