"""Add portfolio_id to idempotency unique constraint

Revision ID: 95e303bc3700
Revises: d1b3c1897da1
Create Date: 2026-09-22 18:59:35.503451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e303bc3700'
down_revision: Union[str, Sequence[str], None] = 'd1b3c1897da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uix_idempotency_key'), 'idempotency_records', type_='unique')
    op.create_unique_constraint('uix_idempotency_key_portfolio', 'idempotency_records', ['user_id', 'portfolio_id', 'mutation_family', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_idempotency_key_portfolio', 'idempotency_records', type_='unique')
    op.create_unique_constraint(op.f('uix_idempotency_key'), 'idempotency_records', ['user_id', 'mutation_family', 'idempotency_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
