"""Add point-in-time fields to FundamentalData

Revision ID: 9e0d081ca962
Revises: 7cadfe1f564b
Create Date: 2026-09-08 00:59:54.872551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0d081ca962'
down_revision: Union[str, Sequence[str], None] = '7cadfe1f564b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundamental_data', sa.Column('period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fundamental_data', sa.Column('available_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fundamental_data', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundamental_data', 'source')
    op.drop_column('fundamental_data', 'available_at')
    op.drop_column('fundamental_data', 'period_end')
    # ### end Alembic commands ###
