"""baseline

Revision ID: a71cf40768fa
Revises:
Create Date: 2026-09-05 22:41:29.425872

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a71cf40768fa"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
