"""phase02_instrument_master_provider_abstraction

Revision ID: b233039f6894
Revises: ce250a5f1627
Create Date: 2026-09-06 23:07:54.561853

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b233039f6894"
down_revision: str | Sequence[str] | None = "ce250a5f1627"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instruments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("exchange", sa.String(), nullable=False),
        sa.Column(
            "instrument_type",
            sa.Enum("STOCK", "ETF", "INDEX", "CURRENCY", "COMMODITY", name="instrumenttype"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_instruments_exchange"), "instruments", ["exchange"], unique=False)
    op.create_index(op.f("ix_instruments_id"), "instruments", ["id"], unique=False)
    op.create_index(op.f("ix_instruments_is_active"), "instruments", ["is_active"], unique=False)
    op.create_index(op.f("ix_instruments_symbol"), "instruments", ["symbol"], unique=True)
    op.create_table(
        "provider_health",
        sa.Column("provider_name", sa.String(), nullable=False),
        sa.Column("is_healthy", sa.Boolean(), nullable=False),
        sa.Column("last_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("circuit_open", sa.Boolean(), nullable=False),
        sa.Column("circuit_opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("provider_name"),
    )
    op.create_table(
        "provider_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("provider_name", sa.String(), nullable=False),
        sa.Column("provider_symbol", sa.String(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_provider_mappings_id"), "provider_mappings", ["id"], unique=False)
    op.create_index(
        op.f("ix_provider_mappings_instrument_id"),
        "provider_mappings",
        ["instrument_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_mappings_provider_name"),
        "provider_mappings",
        ["provider_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_provider_mappings_provider_name"), table_name="provider_mappings")
    op.drop_index(op.f("ix_provider_mappings_instrument_id"), table_name="provider_mappings")
    op.drop_index(op.f("ix_provider_mappings_id"), table_name="provider_mappings")
    op.drop_table("provider_mappings")
    op.drop_table("provider_health")
    op.drop_index(op.f("ix_instruments_symbol"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_is_active"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_id"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_exchange"), table_name="instruments")
    op.drop_table("instruments")
    op.execute("DROP TYPE IF EXISTS instrumenttype")
    # ### end Alembic commands ###
