"""Phase 30 additions

Revision ID: d1b3c1897da1
Revises: e9644fc68961
Create Date: 2026-09-22 18:29:06.030801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b3c1897da1'
down_revision: Union[str, Sequence[str], None] = 'e9644fc68961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('champion_config_hash', sa.String(length=64), nullable=True),
    sa.Column('frozen_challenger_manifest_hash', sa.String(length=64), nullable=True),
    sa.Column('train_interval_start', sa.DateTime(), nullable=True),
    sa.Column('train_interval_end', sa.DateTime(), nullable=True),
    sa.Column('validation_interval_start', sa.DateTime(), nullable=True),
    sa.Column('validation_interval_end', sa.DateTime(), nullable=True),
    sa.Column('holdout_interval_start', sa.DateTime(), nullable=True),
    sa.Column('holdout_interval_end', sa.DateTime(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('holdout_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('holdout_consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_cycles_id'), 'calibration_cycles', ['id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('mutation_family', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mutation_family', 'idempotency_key', name='uix_idempotency_key')
    )
    op.create_index(op.f('ix_idempotency_records_id'), 'idempotency_records', ['id'], unique=False)
    op.add_column('backtest_jobs', sa.Column('calibration_cycle_id', sa.Integer(), nullable=True))
    op.add_column('backtest_jobs', sa.Column('code_commit_sha', sa.String(length=40), nullable=True))
    op.add_column('backtest_jobs', sa.Column('engine_ver', sa.String(length=50), nullable=True))
    op.add_column('backtest_jobs', sa.Column('lifecycle_ver', sa.String(length=50), nullable=True))
    op.add_column('backtest_jobs', sa.Column('alloc_ver', sa.String(length=50), nullable=True))
    op.add_column('backtest_jobs', sa.Column('exec_ver', sa.String(length=50), nullable=True))
    op.add_column('backtest_jobs', sa.Column('metric_ver', sa.String(length=50), nullable=True))
    op.add_column('backtest_jobs', sa.Column('cal_ver', sa.String(length=50), nullable=True))
    op.add_column('backtest_jobs', sa.Column('config_hash', sa.String(length=64), nullable=True))
    op.add_column('backtest_jobs', sa.Column('frozen_challenger_manifest_hash', sa.String(length=64), nullable=True))
    op.add_column('backtest_jobs', sa.Column('dataset_root_hash', sa.String(length=64), nullable=True))
    op.add_column('backtest_jobs', sa.Column('universe_fingerprint', sa.String(length=64), nullable=True))
    op.add_column('backtest_jobs', sa.Column('benchmark_id', sa.String(length=50), nullable=True))
    op.add_column('backtest_jobs', sa.Column('asset_classes', sa.JSON(), nullable=True))
    op.add_column('backtest_jobs', sa.Column('base_currency', sa.String(length=10), nullable=True))
    op.add_column('backtest_jobs', sa.Column('cost_model', sa.String(length=50), nullable=True))
    op.add_column('backtest_jobs', sa.Column('seed', sa.Integer(), nullable=True))
    op.add_column('backtest_jobs', sa.Column('role', sa.String(length=20), server_default='TRAIN', nullable=False))
    op.create_foreign_key('fk_backtest_jobs_calibration_cycle_id', 'backtest_jobs', 'calibration_cycles', ['calibration_cycle_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_decision_snapshots_instrument'), table_name='decision_snapshots')
    op.drop_index(op.f('idx_ohlcv_daily_time'), table_name='ohlcv_daily')
    op.drop_index(op.f('idx_portfolio_tx_executed_at'), table_name='portfolio_transactions')
    op.create_index(op.f('ix_position_lifecycle_snapshots_id'), 'position_lifecycle_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_position_lifecycle_snapshots_lifecycle_id'), 'position_lifecycle_snapshots', ['lifecycle_id'], unique=False)
    op.create_index(op.f('ix_position_lifecycles_id'), 'position_lifecycles', ['id'], unique=False)
    op.create_index(op.f('ix_position_lifecycles_instrument_id'), 'position_lifecycles', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_position_lifecycles_portfolio_id'), 'position_lifecycles', ['portfolio_id'], unique=False)
    op.drop_index(op.f('idx_trade_journals_portfolio_time'), table_name='trade_journals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_trade_journals_portfolio_time'), 'trade_journals', ['portfolio_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_position_lifecycles_portfolio_id'), table_name='position_lifecycles')
    op.drop_index(op.f('ix_position_lifecycles_instrument_id'), table_name='position_lifecycles')
    op.drop_index(op.f('ix_position_lifecycles_id'), table_name='position_lifecycles')
    op.drop_index(op.f('ix_position_lifecycle_snapshots_lifecycle_id'), table_name='position_lifecycle_snapshots')
    op.drop_index(op.f('ix_position_lifecycle_snapshots_id'), table_name='position_lifecycle_snapshots')
    op.create_index(op.f('idx_portfolio_tx_executed_at'), 'portfolio_transactions', ['portfolio_id', 'executed_at'], unique=False)
    op.create_index(op.f('idx_ohlcv_daily_time'), 'ohlcv_daily', ['instrument_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_decision_snapshots_instrument'), 'decision_snapshots', ['instrument_id', sa.literal_column('calculated_at DESC')], unique=False)
    op.drop_constraint('fk_backtest_jobs_calibration_cycle_id', 'backtest_jobs', type_='foreignkey')
    op.drop_column('backtest_jobs', 'role')
    op.drop_column('backtest_jobs', 'seed')
    op.drop_column('backtest_jobs', 'cost_model')
    op.drop_column('backtest_jobs', 'base_currency')
    op.drop_column('backtest_jobs', 'asset_classes')
    op.drop_column('backtest_jobs', 'benchmark_id')
    op.drop_column('backtest_jobs', 'universe_fingerprint')
    op.drop_column('backtest_jobs', 'dataset_root_hash')
    op.drop_column('backtest_jobs', 'frozen_challenger_manifest_hash')
    op.drop_column('backtest_jobs', 'config_hash')
    op.drop_column('backtest_jobs', 'cal_ver')
    op.drop_column('backtest_jobs', 'metric_ver')
    op.drop_column('backtest_jobs', 'exec_ver')
    op.drop_column('backtest_jobs', 'alloc_ver')
    op.drop_column('backtest_jobs', 'lifecycle_ver')
    op.drop_column('backtest_jobs', 'engine_ver')
    op.drop_column('backtest_jobs', 'code_commit_sha')
    op.drop_column('backtest_jobs', 'calibration_cycle_id')
    op.drop_index(op.f('ix_idempotency_records_id'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_calibration_cycles_id'), table_name='calibration_cycles')
    op.drop_table('calibration_cycles')
    # ### end Alembic commands ###
