"""Add Phase 16 models

Revision ID: e55899f9cbcb
Revises: 9e0d081ca962
Create Date: 2026-09-08 01:08:59.224235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55899f9cbcb'
down_revision: Union[str, Sequence[str], None] = '9e0d081ca962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promotion_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index(op.f('ix_strategy_versions_id'), 'strategy_versions', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_versions_name'), 'strategy_versions', ['name'], unique=False)
    op.create_table('decision_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('return_t1', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('return_t5', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('return_t20', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('return_t60', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('benchmark_t1', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('benchmark_t5', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('benchmark_t20', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('benchmark_t60', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decision_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    op.create_index(op.f('ix_decision_outcomes_id'), 'decision_outcomes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_outcomes_id'), table_name='decision_outcomes')
    op.drop_table('decision_outcomes')
    op.drop_index(op.f('ix_strategy_versions_name'), table_name='strategy_versions')
    op.drop_index(op.f('ix_strategy_versions_id'), table_name='strategy_versions')
    op.drop_table('strategy_versions')
    # ### end Alembic commands ###
