"""Add Phase 07 KAP and News models

Revision ID: f3aff42b8185
Revises: 5e32e9bb5438
Create Date: 2026-09-07 11:19:39.353221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3aff42b8185'
down_revision: Union[str, Sequence[str], None] = '5e32e9bb5438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundamental_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('pe_ratio', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'period', name='uq_fundamental_instrument_period')
    )
    op.create_index(op.f('ix_fundamental_data_id'), 'fundamental_data', ['id'], unique=False)
    op.create_index(op.f('ix_fundamental_data_instrument_id'), 'fundamental_data', ['instrument_id'], unique=False)
    op.create_table('kap_disclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('disclosure_index', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('provider_sentiment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kap_disclosures_disclosure_index'), 'kap_disclosures', ['disclosure_index'], unique=True)
    op.create_index(op.f('ix_kap_disclosures_id'), 'kap_disclosures', ['id'], unique=False)
    op.create_index(op.f('ix_kap_disclosures_instrument_id'), 'kap_disclosures', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_kap_disclosures_published_at'), 'kap_disclosures', ['published_at'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_tier', sa.Integer(), nullable=True),
    sa.Column('provider_sentiment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.create_index(op.f('ix_news_articles_instrument_id'), 'news_articles', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_source_id'), 'news_articles', ['source_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_articles_source_id'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_instrument_id'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_kap_disclosures_published_at'), table_name='kap_disclosures')
    op.drop_index(op.f('ix_kap_disclosures_instrument_id'), table_name='kap_disclosures')
    op.drop_index(op.f('ix_kap_disclosures_id'), table_name='kap_disclosures')
    op.drop_index(op.f('ix_kap_disclosures_disclosure_index'), table_name='kap_disclosures')
    op.drop_table('kap_disclosures')
    op.drop_index(op.f('ix_fundamental_data_instrument_id'), table_name='fundamental_data')
    op.drop_index(op.f('ix_fundamental_data_id'), table_name='fundamental_data')
    op.drop_table('fundamental_data')
    # ### end Alembic commands ###
