"""Add TradeJournal model

Revision ID: f6b73d7d3ab3
Revises: ae1e84c7c79c
Create Date: 2026-09-07 13:32:34.939763

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f6b73d7d3ab3'
down_revision: str | Sequence[str] | None = 'ae1e84c7c79c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('setup', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('emotion', sa.String(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['portfolio_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_journals_id'), 'trade_journals', ['id'], unique=False)
    op.create_index(op.f('ix_trade_journals_portfolio_id'), 'trade_journals', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_trade_journals_transaction_id'), 'trade_journals', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_journals_transaction_id'), table_name='trade_journals')
    op.drop_index(op.f('ix_trade_journals_portfolio_id'), table_name='trade_journals')
    op.drop_index(op.f('ix_trade_journals_id'), table_name='trade_journals')
    op.drop_table('trade_journals')
    # ### end Alembic commands ###
