"""Add asset classes and multi currency support

Revision ID: f95a6200b76f
Revises: ea09294646b8
Create Date: 2026-09-20 00:11:26.928315

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f95a6200b76f'
down_revision: str | Sequence[str] | None = 'ea09294646b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create enum type first to be safe
    assetclass_enum = sa.Enum('BIST_EQUITY', 'US_EQUITY', 'GOLD', 'FX_REFERENCE', name='assetclass')
    assetclass_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('instruments', sa.Column('asset_class', assetclass_enum, server_default='BIST_EQUITY', nullable=False))
    op.add_column('instruments', sa.Column('currency', sa.String(length=3), server_default='TRY', nullable=False))

    op.add_column('portfolio_transactions', sa.Column('native_price', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('portfolio_transactions', sa.Column('native_currency', sa.String(length=3), nullable=True))
    op.add_column('portfolio_transactions', sa.Column('fx_rate_to_base', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('portfolio_transactions', sa.Column('execution_source', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_transactions', 'execution_source')
    op.drop_column('portfolio_transactions', 'fx_rate_to_base')
    op.drop_column('portfolio_transactions', 'native_currency')
    op.drop_column('portfolio_transactions', 'native_price')

    op.drop_column('instruments', 'currency')
    op.drop_column('instruments', 'asset_class')

    # Drop enum
    sa.Enum(name='assetclass').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
